name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: cd ./front && npm install && yarn build && cd ../

#      - name: Run lint (опционально)
#        run: cd ./front && npm run lint

      - name: Install commitlint
        run: npm install --save-dev @commitlint/{cli,config-conventional}
      - name: Run commitlint
        run: npx commitlint --from HEAD~1 --to HEAD --verbose
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose
#
#      - name: Run tests
#        run: npm test

  check-merge:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check PR status
        run: |
          if [ ${{ github.event.pull_request.mergeable }} == 'false' ]; then
            echo "PR checks failed, unable to merge."
            exit 1
          fi
