name: Commitlint

on:
  push:
    branches:
      - '*'
jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install commitlint
        run: npm install --save-dev @commitlint/{cli,config-conventional}
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
#          npx commitlint --version
#      - name: Install commitlint
#        run: |
#          npm install conventional-changelog-conventionalcommits
#          npm install commitlint@latest


#      - name: Run commitlint
#        run: npx commitlint --from HEAD~1 --to HEAD --verbose

#      - name: Validate current commit (last commit) with commitlint
#        if: github.event_name == 'push'
#        run: npx commitlint --from HEAD~1 --to HEAD --verbose
#
#      - name: Validate PR commits with commitlint
#        if: github.event_name == 'pull_request'
#        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
